apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: proxy-image
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: localhost-machine
spec:
  type: ExternalName
  externalName: host.docker.internal